spring:
  datasource:
    hikari:
      username: sa
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  h2:
    console:
      enabled: true